spring:
  application:
    name: comprebem
  datasource:
    driver-class: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_udemy
    username: root
    password: limaamor76
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
    open-in-view: false
  logging:
    level:
      br.com.luis: DEBUG
